# Generated by Django 4.0.6 on 2022-07-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Escribi_el_titulo_de_la_pestana', max_length=200),
        ),
    ]
