# Generated by Django 4.0.6 on 2022-07-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0003_alter_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='titulo_tag',
        ),
    ]
