# Generated by Django 4.0.6 on 2022-07-27 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ourblog', '0004_rename_author_post_autor_rename_title_post_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_tag', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
