# Generated by Django 4.0.6 on 2022-07-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0007_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=200),
        ),
    ]
