# Generated by Django 4.0.6 on 2022-07-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0008_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoria',
        ),
    ]
