# Generated by Django 4.0.6 on 2022-08-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
